name: My first workflow
on: [push, pull_request]
jobs:
  job_1:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: my first step
        uses: actions/checkout@v2

      - name: my second step
        uses: echo "Hello world"

      - name: run python
        run: python main.py
        shell: bash

      - name: my second step
        run: echo "Hello world"
        shell: bash

      - name: my third step
        run:
          echo "first hello"
          echo "second hello!"
        shell: bash

      - name: The job has succeeded
        if: ${{ sucess() }}
        run: echo "successfully completed"
  deploy: # cloud
