name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Super-Linter
      - uses: github/super-linter@v5.7.2
